# Generated by Django 6.0.1 on 2026-01-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='badge',
            field=models.CharField(blank=True, help_text="e.g., 'Core Service', 'Local Works'", max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.CharField(blank=True, help_text="Comma-separated tags, e.g., 'commercial, institutional'", max_length=200),
        ),
    ]
