# Generated by Django 6.0.1 on 2026-01-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaMosaicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('src', models.URLField(help_text='Main media URL (image or video)')),
                ('thumbnail', models.URLField(blank=True, help_text='Thumbnail URL (used for previews)')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(help_text='e.g. education, housing, football-club', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Media Mosaic Item',
                'verbose_name_plural': 'Media Mosaic Items',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='job_type',
            field=models.CharField(choices=[('All Jobs', 'All Jobs'), ('Full Time', 'Full Time'), ('Half Time', 'Half Time'), ('Remote', 'Remote'), ('In Office', 'In Office')], default='Full Time', max_length=50),
        ),
    ]
