# Generated by Django 6.0.1 on 2026-01-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_service_badge_service_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('job_type', models.CharField(choices=[('All Jobs', 'All Jobs'), ('Full Time', 'Full Time'), ('Half Time', 'Half Time'), ('Remote', 'Remote'), ('In Office', 'In Office')], default='All Jobs', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
