# Generated by Django 6.0.1 on 2026-01-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_mediamosaicitem_jobapplication_accepted_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamosaicitem',
            name='src',
            field=models.FileField(help_text='Upload image or video file', upload_to='media_mosaic/'),
        ),
        migrations.AlterField(
            model_name='mediamosaicitem',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Required for videos only', null=True, upload_to='media_mosaic/thumbnails/'),
        ),
    ]
