# Generated by Django 6.0.1 on 2026-01-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(help_text='The system instructions/context for the AI chatbot.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chatbot Configuration',
                'verbose_name_plural': 'Chatbot Configuration',
            },
        ),
        migrations.CreateModel(
            name='CompanyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Project Complete'", max_length=100)),
                ('value', models.CharField(help_text="e.g., '13'", max_length=50)),
                ('suffix', models.CharField(blank=True, help_text="e.g., '+', '%'", max_length=10)),
                ('icon_class', models.CharField(blank=True, help_text="e.g., 'icon-scaffolding'", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Order to display on the page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
