# Generated by Django 6.0.1 on 2026-01-28 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_mediamosaicitem_src_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_turnover', models.DecimalField(decimal_places=2, help_text='Current fiscal year turnover in ETB', max_digits=15)),
                ('current_turnover_year', models.CharField(help_text="e.g., '2024/25'", max_length=20)),
                ('total_projects', models.IntegerField(default=0, help_text='Total number of projects')),
                ('portfolio_value', models.DecimalField(decimal_places=2, help_text='Total portfolio value in ETB', max_digits=15)),
                ('completed_projects', models.IntegerField(default=0, help_text='Number of completed projects')),
                ('active_works', models.IntegerField(default=0, help_text='Number of active/ongoing projects')),
                ('yoy_growth', models.DecimalField(decimal_places=2, help_text='Year-over-year growth percentage', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this is the active metrics set')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financial Metrics',
                'verbose_name_plural': 'Financial Metrics',
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text="e.g., '2020/21'", max_length=20, unique=True)),
                ('turnover', models.DecimalField(decimal_places=2, help_text='Annual turnover in ETB', max_digits=15)),
                ('year_start', models.DateField(blank=True, help_text='Start date of fiscal year', null=True)),
                ('year_end', models.DateField(blank=True, help_text='End date of fiscal year', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this fiscal year is currently active')),
                ('order', models.IntegerField(default=0, help_text='Order for display (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fiscal Year',
                'verbose_name_plural': 'Fiscal Years',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(help_text='Date of the portfolio snapshot')),
                ('completed_count', models.IntegerField(default=0)),
                ('completed_value', models.DecimalField(decimal_places=2, help_text='Total value of completed projects in ETB', max_digits=15)),
                ('ongoing_count', models.IntegerField(default=0)),
                ('ongoing_value', models.DecimalField(decimal_places=2, help_text='Total value of ongoing projects in ETB', max_digits=15)),
                ('priority_count', models.IntegerField(default=0)),
                ('priority_value', models.DecimalField(decimal_places=2, help_text='Total value of priority projects in ETB', max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, help_text='Total portfolio value in ETB', max_digits=15)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this is the active snapshot')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio Status',
                'verbose_name_plural': 'Portfolio Status',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='FinanceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, help_text='Project description')),
                ('client', models.CharField(help_text='Client/Administration name', max_length=300)),
                ('value', models.DecimalField(decimal_places=2, help_text='Project value in ETB', max_digits=15)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Priority', 'Priority')], default='Ongoing', max_length=50)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('is_outstanding', models.BooleanField(default=False, help_text='Show in outstanding works section')),
                ('contract_date', models.CharField(blank=True, help_text="e.g., 'Feb 14, 2017 E.C.'", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Order for display within fiscal year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='web.fiscalyear')),
            ],
            options={
                'verbose_name': 'Finance Project',
                'verbose_name_plural': 'Finance Projects',
                'ordering': ['fiscal_year__order', 'order', '-value'],
            },
        ),
    ]
