# Generated by Django 6.0.1 on 2026-02-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_financialmetrics_fiscalyear_portfoliostatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialWelfareStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='A brief summary of the story.')),
                ('image', models.ImageField(help_text='Image for the carousel slide.', upload_to='social_welfare/stories/')),
                ('link', models.URLField(blank=True, help_text='Optional link to the full story.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Welfare Story',
                'verbose_name_plural': 'Social Welfare Stories',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
