# Generated by Django 6.0.1 on 2026-02-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediamosaicitem',
            name='description',
            field=models.TextField(default='description'),
        ),
    ]
