# Generated by Django 6.0.1 on 2026-02-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mediamosaicitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamosaicitem',
            name='category',
            field=models.CharField(default='all', max_length=50),
        ),
    ]
