# Generated by Django 6.0.1 on 2026-02-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mediamosaicitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='slider/videos/'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slider/images/'),
        ),
    ]
